### ISSUE TITLE
Moss error `output.decode`

### ISSUE THREAD

**Issue by mkijowski** [wrightedu/CSE-Discord-Bot#289]
**Describe the bug**
Moss doesn't work

**To Reproduce**
run moss, check bot output logs in AWS

**Expected behavior**

**Screenshots**
```bash
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/app_commands/commands.py", line 861, in _do_call
    return await self._callback(self.binding, interaction, **params)  # type: ignore
  File "/home/ubuntu/master/Cogs/MOSS.py", line 156, in moss
    link = output.decode().split("\n")[-2]
IndexError: list index out of range

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/app_commands/tree.py", line 1242, in _call
    await command._invoke_with_namespace(interaction, namespace)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/app_commands/commands.py", line 887, in _invoke_with_namespace
    return await self._do_call(interaction, transformed_values)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/app_commands/commands.py", line 880, in _do_call
    raise CommandInvokeError(self, e) from e
discord.app_commands.errors.CommandInvokeError: Command 'moss' raised an exception: IndexError: list index out of range
```

**Additional context**
Would need a check on `output.decode` to see if its empty (or valid?)

**Comment by mkijowski** [comment]
Its line 146 of the Moss cog: 

```python
        moss_command = f'python ./utils/WSU_mossScript.py --id {moss_id}'
``` 
needs to be `python3` not `python`

**Comment by mkijowski** [comment]
git blame `99f5d16a (Makaela Sellers 2024-02-02 17:04:27 -0500 146) `  now go forth and fix it :p
